{% set version = "8.9.1" %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz
  sha256: 32491b7fcc4696b2cdead45c47e52ad16bbed8f78885d32e873952fee0f971e1

build:
  number: 0
  ignore_prefix_files:
    - bin/node

requirements:
  build:
    # node's build scripts find and use MSVC 2015, regardless of conda's setting.
    - toolchain
    - vs2015_runtime  # [win]
    # nodejs requires Python 2.7 to build,
    # but nodejs paths are too long for Python 2.7 on Windows.
    # Run conda-build with Python 3.6 on Windows,
    # and activate Python 2 in bld.bat.
    - python          2.7.* # [not win]
    - python          3.6.* # [win]
    - gcc             # [linux]
  run:
    - vs2015_runtime   # [win]
    - libgcc           # [linux]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
